Update solrconfig for admin interface
This is now separate from each core `conf`.

Error was:
```
ERROR: Error CREATEing SolrCore 'blacklight-core': Unable to create core
[blacklight-core] Caused by: org.apache.solr.handler.admin.AdminHandlers
```